In [1]:
import pandas as pd

In [2]:
2+2

4

In [3]:
# Alberta Enrolment Analytics

This notebook cleans Statistics Canada enrolment data.

SyntaxError: invalid syntax (2354572768.py, line 3)

# Alberta Enrolment Analytics

This notebook cleans Statistics Canada enrolment data.

# Alberta Post-Secondary Enrolment Analytics

## 01 - Data Cleaning and Preparation

### Objective

Prepare Statistics Canada post-secondary enrolment data for analysis of historical enrolment trends across Alberta institutions from 2014/15 through 2023/24.

### Data Source

Statistics Canada — Postsecondary enrolment data.

### Cleaning Goals

- Preserve the original source data
- Inspect the dataset structure
- Identify missing or inconsistent values
- Standardize institution and academic-year fields
- Convert enrolment values into an analysis-ready format
- Validate cleaned values against the original source
- Export a clean dataset for subsequent analysis

In [4]:
import pandas as pd

In [8]:
file_path = "../data/raw/statcan_alberta_enrolment_2014_2024_raw.csv"

In [6]:
df_raw.head()

NameError: name 'df_raw' is not defined

In [9]:
import os

print(os.getcwd())

C:\Users\MDDDR\Documents\Alberta-Enrolment-Analytics\notebooks

In [10]:
print(os.listdir("../data/raw"))

['statcan_alberta_enrolment_2014_2024_raw.csv']

In [12]:
import pandas as pd

file_path = "../data/raw/statcan_alberta_enrolment_2014_2024_raw.csv"

df_raw = pd.read_csv(
    file_path,
    skiprows=15
)

df_raw.head()

,Geography and institutions,2014 / 2015,2015 / 2016,2016 / 2017,2017 / 2018,2018 / 2019,2019 / 2020,2020 / 2021,2021 / 2022,2022 / 2023,2023 / 2024
0,NaN,Number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alberta 11,"184,026","185,679","190,947","194,010","200,391","203,823","203,523","203,580","205,734","216,957"
2,"University of Alberta, Alberta","38,520","37,716","38,244","39,363","40,017","40,590","42,270","43,905","44,535","45,306"
3,"Athabasca University, Alberta","17,577","17,331","17,346","16,941","18,561","18,930","20,535","17,127","16,458","16,005"
4,"University of Calgary, Alberta","31,308","31,749","33,189","33,903","34,785","35,556","36,543","37,200","37,680","38,715"

In [13]:
df_raw.shape

(44, 11)

In [14]:
df_raw.columns.tolist()

['Geography and institutions',
 '2014 / 2015',
 '2015 / 2016',
 '2016 / 2017',
 '2017 / 2018',
 '2018 / 2019',
 '2019 / 2020',
 '2020 / 2021',
 '2021 / 2022',
 '2022 / 2023',
 '2023 / 2024']

In [15]:
df_raw.head(10)

,Geography and institutions,2014 / 2015,2015 / 2016,2016 / 2017,2017 / 2018,2018 / 2019,2019 / 2020,2020 / 2021,2021 / 2022,2022 / 2023,2023 / 2024
0,NaN,Number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alberta 11,"184,026","185,679","190,947","194,010","200,391","203,823","203,523","203,580","205,734","216,957"
2,"University of Alberta, Alberta","38,520","37,716","38,244","39,363","40,017","40,590","42,270","43,905","44,535","45,306"
3,"Athabasca University, Alberta","17,577","17,331","17,346","16,941","18,561","18,930","20,535","17,127","16,458","16,005"
4,"University of Calgary, Alberta","31,308","31,749","33,189","33,903","34,785","35,556","36,543","37,200","37,680","38,715"
5,"Burman University, Alberta",474,471,456,435,435,459,390,339,348,333
6,"Concordia University of Edmonton, Alberta","1,506","1,686","1,878","2,001","2,235","2,679","2,997","2,817","2,628","2,568"
7,"University of Lethbridge, Alberta","8,157","8,406","8,568","8,670","8,709","8,949","8,829","9,117","8,553","8,682"
8,"The King's University, Alberta",702,765,780,810,825,834,849,879,810,804
9,"St. Mary's University, Alberta",732,771,789,888,921,999,"1,020","1,032",942,924

In [16]:
df = df_raw.copy()

In [17]:
df.head()

,Geography and institutions,2014 / 2015,2015 / 2016,2016 / 2017,2017 / 2018,2018 / 2019,2019 / 2020,2020 / 2021,2021 / 2022,2022 / 2023,2023 / 2024
0,NaN,Number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alberta 11,"184,026","185,679","190,947","194,010","200,391","203,823","203,523","203,580","205,734","216,957"
2,"University of Alberta, Alberta","38,520","37,716","38,244","39,363","40,017","40,590","42,270","43,905","44,535","45,306"
3,"Athabasca University, Alberta","17,577","17,331","17,346","16,941","18,561","18,930","20,535","17,127","16,458","16,005"
4,"University of Calgary, Alberta","31,308","31,749","33,189","33,903","34,785","35,556","36,543","37,200","37,680","38,715"

In [18]:
df = df.iloc[1:].copy()

In [19]:
df = df.reset_index(drop=True)

In [20]:
df.head()

,Geography and institutions,2014 / 2015,2015 / 2016,2016 / 2017,2017 / 2018,2018 / 2019,2019 / 2020,2020 / 2021,2021 / 2022,2022 / 2023,2023 / 2024
0,Alberta 11,"184,026","185,679","190,947","194,010","200,391","203,823","203,523","203,580","205,734","216,957"
1,"University of Alberta, Alberta","38,520","37,716","38,244","39,363","40,017","40,590","42,270","43,905","44,535","45,306"
2,"Athabasca University, Alberta","17,577","17,331","17,346","16,941","18,561","18,930","20,535","17,127","16,458","16,005"
3,"University of Calgary, Alberta","31,308","31,749","33,189","33,903","34,785","35,556","36,543","37,200","37,680","38,715"
4,"Burman University, Alberta",474,471,456,435,435,459,390,339,348,333

In [21]:
df["Geography and institutions"].tolist()

['Alberta 11',
 'University of Alberta, Alberta',
 'Athabasca University, Alberta',
 'University of Calgary, Alberta',
 'Burman University, Alberta',
 'Concordia University of Edmonton, Alberta',
 'University of Lethbridge, Alberta',
 "The King's University, Alberta",
 "St. Mary's University, Alberta",
 'Ambrose University, Alberta',
 'Grant MacEwan University, Alberta',
 'Mount Royal University, Alberta',
 'Alberta University of the Arts, Alberta 11',
 'Alberta College of Art and Design, Alberta 11',
 'Bow Valley College, Alberta',
 'Olds College, Alberta',
 'Lakeland College, Alberta',
 'Northwestern Polytechnic, Alberta',
 'Lethbridge College, Alberta',
 'Medicine Hat College, Alberta',
 'Keyano College, Alberta',
 'Red Deer Polytechnic, Alberta',
 'Northern Alberta Institute of Technology, Alberta',
 'Southern Alberta Institute of Technology, Alberta',
 'NorQuest College, Alberta',
 'Northern Lakes College, Alberta',
 'Portage College, Alberta',
 'Symbol legend:',
 '..',
 'Footnotes:',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 'How to cite: Statistics Canada. Table 37-10-0277-01\xa0 Postsecondary enrolments, by detailed field of study, institution, and program and student characteristics',
 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3710027701']

In [22]:
df.dtypes

Geography and institutions    str
2014 / 2015                   str
2015 / 2016                   str
2016 / 2017                   str
2017 / 2018                   str
2018 / 2019                   str
2019 / 2020                   str
2020 / 2021                   str
2021 / 2022                   str
2022 / 2023                   str
2023 / 2024                   str
dtype: object

In [23]:
last_data_row = df[
    df["Geography and institutions"].eq("Portage College, Alberta")
].index[0]

In [24]:
df = df.loc[:last_data_row].copy()
df = df.reset_index(drop=True)

In [25]:
df.tail()

,Geography and institutions,2014 / 2015,2015 / 2016,2016 / 2017,2017 / 2018,2018 / 2019,2019 / 2020,2020 / 2021,2021 / 2022,2022 / 2023,2023 / 2024
22,"Northern Alberta Institute of Technology, Alberta","10,833","11,784","12,687","12,972","13,194","13,242","12,909","12,723","12,123","12,993"
23,"Southern Alberta Institute of Technology, Alberta","14,307","14,268","13,788","13,041","13,587","13,629","12,240","12,312","12,870","15,306"
24,"NorQuest College, Alberta","4,212","5,097","6,111","6,345","7,035","7,536","7,143","7,821","8,781","10,299"
25,"Northern Lakes College, Alberta","1,389","1,185","1,278","1,413","1,416","1,377","1,434","1,581","1,749","1,944"
26,"Portage College, Alberta",759,825,927,933,987,969,885,"1,095","1,398","1,569"

In [26]:
df.shape

(27, 11)

In [27]:
df["Geography and institutions"].tolist()

['Alberta 11',
 'University of Alberta, Alberta',
 'Athabasca University, Alberta',
 'University of Calgary, Alberta',
 'Burman University, Alberta',
 'Concordia University of Edmonton, Alberta',
 'University of Lethbridge, Alberta',
 "The King's University, Alberta",
 "St. Mary's University, Alberta",
 'Ambrose University, Alberta',
 'Grant MacEwan University, Alberta',
 'Mount Royal University, Alberta',
 'Alberta University of the Arts, Alberta 11',
 'Alberta College of Art and Design, Alberta 11',
 'Bow Valley College, Alberta',
 'Olds College, Alberta',
 'Lakeland College, Alberta',
 'Northwestern Polytechnic, Alberta',
 'Lethbridge College, Alberta',
 'Medicine Hat College, Alberta',
 'Keyano College, Alberta',
 'Red Deer Polytechnic, Alberta',
 'Northern Alberta Institute of Technology, Alberta',
 'Southern Alberta Institute of Technology, Alberta',
 'NorQuest College, Alberta',
 'Northern Lakes College, Alberta',
 'Portage College, Alberta']

In [28]:
df = df.rename(
    columns={
        "Geography and institutions": "Institution_Raw"
    }
)

In [29]:
df["Institution"] = (
    df["Institution_Raw"]
    .str.replace(r"\s+11$", "", regex=True)
    .str.replace(r", Alberta$", "", regex=True)
    .str.strip()
)

In [30]:
df[["Institution_Raw", "Institution"]].head(15)

,Institution_Raw,Institution
0,Alberta 11,Alberta
1,"University of Alberta, Alberta",University of Alberta
2,"Athabasca University, Alberta",Athabasca University
3,"University of Calgary, Alberta",University of Calgary
4,"Burman University, Alberta",Burman University
5,"Concordia University of Edmonton, Alberta",Concordia University of Edmonton
6,"University of Lethbridge, Alberta",University of Lethbridge
7,"The King's University, Alberta",The King's University
8,"St. Mary's University, Alberta",St. Mary's University
9,"Ambrose University, Alberta",Ambrose University
10,"Grant MacEwan University, Alberta",Grant MacEwan University
11,"Mount Royal University, Alberta",Mount Royal University
12,"Alberta University of the Arts, Alberta 11",Alberta University of the Arts
13,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design
14,"Bow Valley College, Alberta",Bow Valley College

In [31]:
year_columns = [
    "2014 / 2015",
    "2015 / 2016",
    "2016 / 2017",
    "2017 / 2018",
    "2018 / 2019",
    "2019 / 2020",
    "2020 / 2021",
    "2021 / 2022",
    "2022 / 2023",
    "2023 / 2024"
]

In [32]:
for col in year_columns:
    df[col] = (
        df[col]
        .str.replace(",", "", regex=False)
        .pipe(pd.to_numeric, errors="coerce")
    )

In [33]:
df.dtypes

Institution_Raw        str
2014 / 2015        float64
2015 / 2016        float64
2016 / 2017        float64
2017 / 2018        float64
2018 / 2019        float64
2019 / 2020        float64
2020 / 2021        float64
2021 / 2022        float64
2022 / 2023        float64
2023 / 2024        float64
Institution            str
dtype: object

In [34]:
df[df["Institution"] == "University of Alberta"]

,Institution_Raw,2014 / 2015,2015 / 2016,2016 / 2017,2017 / 2018,2018 / 2019,2019 / 2020,2020 / 2021,2021 / 2022,2022 / 2023,2023 / 2024,Institution
1,"University of Alberta, Alberta",38520.0,37716.0,38244.0,39363.0,40017.0,40590.0,42270.0,43905.0,44535.0,45306.0,University of Alberta

In [35]:
df_long = df.melt(
    id_vars=["Institution_Raw", "Institution"],
    value_vars=year_columns,
    var_name="Academic_Year",
    value_name="Enrolment"
)

In [36]:
df_long.head(15)

,Institution_Raw,Institution,Academic_Year,Enrolment
0,Alberta 11,Alberta,2014 / 2015,184026.0
1,"University of Alberta, Alberta",University of Alberta,2014 / 2015,38520.0
2,"Athabasca University, Alberta",Athabasca University,2014 / 2015,17577.0
3,"University of Calgary, Alberta",University of Calgary,2014 / 2015,31308.0
4,"Burman University, Alberta",Burman University,2014 / 2015,474.0
5,"Concordia University of Edmonton, Alberta",Concordia University of Edmonton,2014 / 2015,1506.0
6,"University of Lethbridge, Alberta",University of Lethbridge,2014 / 2015,8157.0
7,"The King's University, Alberta",The King's University,2014 / 2015,702.0
8,"St. Mary's University, Alberta",St. Mary's University,2014 / 2015,732.0
9,"Ambrose University, Alberta",Ambrose University,2014 / 2015,519.0
10,"Grant MacEwan University, Alberta",Grant MacEwan University,2014 / 2015,15870.0
11,"Mount Royal University, Alberta",Mount Royal University,2014 / 2015,12372.0
12,"Alberta University of the Arts, Alberta 11",Alberta University of the Arts,2014 / 2015,NaN
13,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,2014 / 2015,1116.0
14,"Bow Valley College, Alberta",Bow Valley College,2014 / 2015,6891.0

In [37]:
df_long.shape

(270, 4)

In [38]:
df_long["Academic_Year"] = (
    df_long["Academic_Year"]
    .str.replace(" ", "", regex=False)
)

In [39]:
df_long["Academic_Year"].unique()

<ArrowStringArray>
['2014/2015', '2015/2016', '2016/2017', '2017/2018', '2018/2019', '2019/2020',
 '2020/2021', '2021/2022', '2022/2023', '2023/2024']
Length: 10, dtype: str

In [40]:
df_long["Academic_Year_Start"] = (
    df_long["Academic_Year"]
    .str[:4]
    .astype(int)
)

In [41]:
df_long["Academic_Year_End"] = (
    df_long["Academic_Year_Start"] + 1
)

In [42]:
df_long[
    ["Academic_Year", "Academic_Year_Start", "Academic_Year_End"]
].drop_duplicates()

    Academic_Year  Academic_Year_Start  Academic_Year_End
0       2014/2015                 2014               2015
27      2015/2016                 2015               2016
54      2016/2017                 2016               2017
81      2017/2018                 2017               2018
108     2018/2019                 2018               2019
135     2019/2020                 2019               2020
162     2020/2021                 2020               2021
189     2021/2022                 2021               2022
216     2022/2023                 2022               2023
243     2023/2024                 2023               2024

In [43]:
df_long["Province"] = "Alberta"

In [44]:
df_long["Record_Type"] = df_long["Institution"].apply(
    lambda x: "Province Total" if x == "Alberta" else "Institution"
)

In [45]:
df_long["Record_Type"].value_counts()

Record_Type
Institution       260
Province Total     10
Name: count, dtype: int64

In [46]:
df_long = df_long.sort_values(
    by=["Institution", "Academic_Year_Start"]
).reset_index(drop=True)

In [47]:
df_long.head(15)

,Institution_Raw,Institution,Academic_Year,Enrolment,Academic_Year_Start,Academic_Year_End,Province,Record_Type
0,Alberta 11,Alberta,2014/2015,184026.0,2014,2015,Alberta,Province Total
1,Alberta 11,Alberta,2015/2016,185679.0,2015,2016,Alberta,Province Total
2,Alberta 11,Alberta,2016/2017,190947.0,2016,2017,Alberta,Province Total
3,Alberta 11,Alberta,2017/2018,194010.0,2017,2018,Alberta,Province Total
4,Alberta 11,Alberta,2018/2019,200391.0,2018,2019,Alberta,Province Total
5,Alberta 11,Alberta,2019/2020,203823.0,2019,2020,Alberta,Province Total
6,Alberta 11,Alberta,2020/2021,203523.0,2020,2021,Alberta,Province Total
7,Alberta 11,Alberta,2021/2022,203580.0,2021,2022,Alberta,Province Total
8,Alberta 11,Alberta,2022/2023,205734.0,2022,2023,Alberta,Province Total
9,Alberta 11,Alberta,2023/2024,216957.0,2023,2024,Alberta,Province Total
10,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,2014/2015,1116.0,2014,2015,Alberta,Institution
11,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,2015/2016,1158.0,2015,2016,Alberta,Institution
12,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,2016/2017,1140.0,2016,2017,Alberta,Institution
13,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,2017/2018,1107.0,2017,2018,Alberta,Institution
14,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,2018/2019,NaN,2018,2019,Alberta,Institution

In [48]:
ualberta = df_long[
    df_long["Institution"] == "University of Alberta"
].copy()

ualberta

,Institution_Raw,Institution,Academic_Year,Enrolment,Academic_Year_Start,Academic_Year_End,Province,Record_Type
240,"University of Alberta, Alberta",University of Alberta,2014/2015,38520.0,2014,2015,Alberta,Institution
241,"University of Alberta, Alberta",University of Alberta,2015/2016,37716.0,2015,2016,Alberta,Institution
242,"University of Alberta, Alberta",University of Alberta,2016/2017,38244.0,2016,2017,Alberta,Institution
243,"University of Alberta, Alberta",University of Alberta,2017/2018,39363.0,2017,2018,Alberta,Institution
244,"University of Alberta, Alberta",University of Alberta,2018/2019,40017.0,2018,2019,Alberta,Institution
245,"University of Alberta, Alberta",University of Alberta,2019/2020,40590.0,2019,2020,Alberta,Institution
246,"University of Alberta, Alberta",University of Alberta,2020/2021,42270.0,2020,2021,Alberta,Institution
247,"University of Alberta, Alberta",University of Alberta,2021/2022,43905.0,2021,2022,Alberta,Institution
248,"University of Alberta, Alberta",University of Alberta,2022/2023,44535.0,2022,2023,Alberta,Institution
249,"University of Alberta, Alberta",University of Alberta,2023/2024,45306.0,2023,2024,Alberta,Institution

## Data Quality Validation

The transformed dataset was evaluated for missing values, duplicate institution-year observations, negative enrolment values, and expected record counts before being exported for analysis.

In [49]:
print("Dataset shape:", df_long.shape)

print("\nMissing values:")
print(df_long.isna().sum())

print(
    "\nDuplicate institution-year records:",
    df_long.duplicated(
        subset=["Institution", "Academic_Year"]
    ).sum()
)

print(
    "\nNegative enrolment values:",
    (df_long["Enrolment"] < 0).sum()
)

print(
    "\nNumber of academic years:",
    df_long["Academic_Year"].nunique()
)

print(
    "\nNumber of institutional records:",
    df_long.loc[
        df_long["Record_Type"] == "Institution",
        "Institution"
    ].nunique()
)

Dataset shape: (270, 8)

Missing values:
Institution_Raw         0
Institution             0
Academic_Year           0
Enrolment              10
Academic_Year_Start     0
Academic_Year_End       0
Province                0
Record_Type             0
dtype: int64

Duplicate institution-year records: 0

Negative enrolment values: 0

Number of academic years: 10

Number of institutional records: 26

In [50]:
missing_enrolment = df_long[
    df_long["Enrolment"].isna()
]

missing_enrolment[
    [
        "Institution_Raw",
        "Institution",
        "Academic_Year",
        "Enrolment"
    ]
]

,Institution_Raw,Institution,Academic_Year,Enrolment
14,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,2018/2019,NaN
15,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,2019/2020,NaN
16,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,2020/2021,NaN
17,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,2021/2022,NaN
18,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,2022/2023,NaN
19,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,2023/2024,NaN
20,"Alberta University of the Arts, Alberta 11",Alberta University of the Arts,2014/2015,NaN
21,"Alberta University of the Arts, Alberta 11",Alberta University of the Arts,2015/2016,NaN
22,"Alberta University of the Arts, Alberta 11",Alberta University of the Arts,2016/2017,NaN
23,"Alberta University of the Arts, Alberta 11",Alberta University of the Arts,2017/2018,NaN

In [52]:
for col in year_columns:
    non_numeric = df[
        pd.to_numeric(
            df[col].astype(str).str.replace(",", "", regex=False),
            errors="coerce"
        ).isna()
    ][["Institution_Raw", col]]

    if not non_numeric.empty:
        print(f"\n{col}")
        print(non_numeric.to_string(index=False))

2014 / 2015
                           Institution_Raw  2014 / 2015
Alberta University of the Arts, Alberta 11          NaN

2015 / 2016
                           Institution_Raw  2015 / 2016
Alberta University of the Arts, Alberta 11          NaN

2016 / 2017
                           Institution_Raw  2016 / 2017
Alberta University of the Arts, Alberta 11          NaN

2017 / 2018
                           Institution_Raw  2017 / 2018
Alberta University of the Arts, Alberta 11          NaN

2018 / 2019
                              Institution_Raw  2018 / 2019
Alberta College of Art and Design, Alberta 11          NaN

2019 / 2020
                              Institution_Raw  2019 / 2020
Alberta College of Art and Design, Alberta 11          NaN

2020 / 2021
                              Institution_Raw  2020 / 2021
Alberta College of Art and Design, Alberta 11          NaN

2021 / 2022
                              Institution_Raw  2021 / 2022
Alberta College of Art and Design, Alberta 11          NaN

2022 / 2023
                              Institution_Raw  2022 / 2023
Alberta College of Art and Design, Alberta 11          NaN

2023 / 2024
                              Institution_Raw  2023 / 2024
Alberta College of Art and Design, Alberta 11          NaN

In [53]:
missing_enrolment.groupby("Institution").size()

Institution
Alberta College of Art and Design    6
Alberta University of the Arts       4
dtype: int64

#The Alberta University of the Arts (AUArts) was previously known as the Alberta College of Art and Design (ACAD). It officially changed its name to #the Alberta University of the Arts on February 1, 2019, after receiving official university status.

In [54]:
df_long[
    df_long["Institution"].isin([
        "Alberta University of the Arts",
        "Alberta College of Art and Design"
    ])
][
    ["Institution", "Academic_Year", "Enrolment"]
].sort_values(
    ["Academic_Year", "Institution"]
)

                          Institution Academic_Year  Enrolment
10  Alberta College of Art and Design     2014/2015     1116.0
20     Alberta University of the Arts     2014/2015        NaN
11  Alberta College of Art and Design     2015/2016     1158.0
21     Alberta University of the Arts     2015/2016        NaN
12  Alberta College of Art and Design     2016/2017     1140.0
22     Alberta University of the Arts     2016/2017        NaN
13  Alberta College of Art and Design     2017/2018     1107.0
23     Alberta University of the Arts     2017/2018        NaN
14  Alberta College of Art and Design     2018/2019        NaN
24     Alberta University of the Arts     2018/2019     1077.0
15  Alberta College of Art and Design     2019/2020        NaN
25     Alberta University of the Arts     2019/2020     1143.0
16  Alberta College of Art and Design     2020/2021        NaN
26     Alberta University of the Arts     2020/2021     1110.0
17  Alberta College of Art and Design     2021/2022        NaN
27     Alberta University of the Arts     2021/2022     1089.0
18  Alberta College of Art and Design     2022/2023        NaN
28     Alberta University of the Arts     2022/2023     1131.0
19  Alberta College of Art and Design     2023/2024        NaN
29     Alberta University of the Arts     2023/2024     1200.0

In [55]:
df_long["Institution_Standardized"] = df_long["Institution"]

In [56]:
df_long.loc[
    df_long["Institution"].isin([
        "Alberta College of Art and Design",
        "Alberta University of the Arts"
    ]),
    "Institution_Standardized"
] = "Alberta University of the Arts"

In [57]:
df_long[
    df_long["Institution_Standardized"] == "Alberta University of the Arts"
][
    [
        "Institution",
        "Institution_Standardized",
        "Academic_Year",
        "Enrolment"
    ]
].sort_values("Academic_Year")

,Institution,Institution_Standardized,Academic_Year,Enrolment
10,Alberta College of Art and Design,Alberta University of the Arts,2014/2015,1116.0
20,Alberta University of the Arts,Alberta University of the Arts,2014/2015,NaN
11,Alberta College of Art and Design,Alberta University of the Arts,2015/2016,1158.0
21,Alberta University of the Arts,Alberta University of the Arts,2015/2016,NaN
12,Alberta College of Art and Design,Alberta University of the Arts,2016/2017,1140.0
22,Alberta University of the Arts,Alberta University of the Arts,2016/2017,NaN
13,Alberta College of Art and Design,Alberta University of the Arts,2017/2018,1107.0
23,Alberta University of the Arts,Alberta University of the Arts,2017/2018,NaN
14,Alberta College of Art and Design,Alberta University of the Arts,2018/2019,NaN
24,Alberta University of the Arts,Alberta University of the Arts,2018/2019,1077.0
15,Alberta College of Art and Design,Alberta University of the Arts,2019/2020,NaN
25,Alberta University of the Arts,Alberta University of the Arts,2019/2020,1143.0
16,Alberta College of Art and Design,Alberta University of the Arts,2020/2021,NaN
26,Alberta University of the Arts,Alberta University of the Arts,2020/2021,1110.0
17,Alberta College of Art and Design,Alberta University of the Arts,2021/2022,NaN
27,Alberta University of the Arts,Alberta University of the Arts,2021/2022,1089.0
18,Alberta College of Art and Design,Alberta University of the Arts,2022/2023,NaN
28,Alberta University of the Arts,Alberta University of the Arts,2022/2023,1131.0
19,Alberta College of Art and Design,Alberta University of the Arts,2023/2024,NaN
29,Alberta University of the Arts,Alberta University of the Arts,2023/2024,1200.0

In [58]:
df_long = df_long[
    ~(
        (df_long["Institution_Standardized"] == "Alberta University of the Arts")
        & (df_long["Enrolment"].isna())
    )
].copy()

In [59]:
df_long = df_long.reset_index(drop=True)

In [60]:
df_long[
    df_long["Institution_Standardized"] == "Alberta University of the Arts"
][
    [
        "Institution",
        "Institution_Standardized",
        "Academic_Year",
        "Enrolment"
    ]
].sort_values("Academic_Year")

,Institution,Institution_Standardized,Academic_Year,Enrolment
10,Alberta College of Art and Design,Alberta University of the Arts,2014/2015,1116.0
11,Alberta College of Art and Design,Alberta University of the Arts,2015/2016,1158.0
12,Alberta College of Art and Design,Alberta University of the Arts,2016/2017,1140.0
13,Alberta College of Art and Design,Alberta University of the Arts,2017/2018,1107.0
14,Alberta University of the Arts,Alberta University of the Arts,2018/2019,1077.0
15,Alberta University of the Arts,Alberta University of the Arts,2019/2020,1143.0
16,Alberta University of the Arts,Alberta University of the Arts,2020/2021,1110.0
17,Alberta University of the Arts,Alberta University of the Arts,2021/2022,1089.0
18,Alberta University of the Arts,Alberta University of the Arts,2022/2023,1131.0
19,Alberta University of the Arts,Alberta University of the Arts,2023/2024,1200.0

In [61]:
df_long.isna().sum()

Institution_Raw             0
Institution                 0
Academic_Year               0
Enrolment                   0
Academic_Year_Start         0
Academic_Year_End           0
Province                    0
Record_Type                 0
Institution_Standardized    0
dtype: int64

In [62]:
df_long.shape

(260, 9)

In [63]:
df_long.loc[
    df_long["Record_Type"] == "Institution",
    "Institution_Standardized"
].nunique()

25

In [64]:
institution_counts = (
    df_long[
        df_long["Record_Type"] == "Institution"
    ]
    .groupby("Institution_Standardized")
    ["Academic_Year"]
    .nunique()
    .sort_values()
)

institution_counts

Institution_Standardized
Alberta University of the Arts              10
Ambrose University                          10
Athabasca University                        10
Bow Valley College                          10
Burman University                           10
Concordia University of Edmonton            10
Grant MacEwan University                    10
Keyano College                              10
Lakeland College                            10
Lethbridge College                          10
Medicine Hat College                        10
Mount Royal University                      10
NorQuest College                            10
Northern Alberta Institute of Technology    10
Northern Lakes College                      10
Northwestern Polytechnic                    10
Olds College                                10
Portage College                             10
Red Deer Polytechnic                        10
Southern Alberta Institute of Technology    10
St. Mary's University                       10
The King's University                       10
University of Alberta                       10
University of Calgary                       10
University of Lethbridge                    10
Name: Academic_Year, dtype: int64

## Historical Institution Name Harmonization

During data-quality review, Alberta College of Art and Design and
Alberta University of the Arts appeared as separate Statistics Canada
records with mutually exclusive reporting periods.

The historical and current names were standardized under
"Alberta University of the Arts" for longitudinal analysis while the
original source institution name was retained for traceability.

Rows associated with the inactive institution name and containing no
reported enrolment value were removed rather than interpreted as zero
enrolment.

In [65]:
df_long.shape

(260, 9)

In [66]:
df_long.isna().sum()

Institution_Raw             0
Institution                 0
Academic_Year               0
Enrolment                   0
Academic_Year_Start         0
Academic_Year_End           0
Province                    0
Record_Type                 0
Institution_Standardized    0
dtype: int64

In [67]:
institution_counts

Institution_Standardized
Alberta University of the Arts              10
Ambrose University                          10
Athabasca University                        10
Bow Valley College                          10
Burman University                           10
Concordia University of Edmonton            10
Grant MacEwan University                    10
Keyano College                              10
Lakeland College                            10
Lethbridge College                          10
Medicine Hat College                        10
Mount Royal University                      10
NorQuest College                            10
Northern Alberta Institute of Technology    10
Northern Lakes College                      10
Northwestern Polytechnic                    10
Olds College                                10
Portage College                             10
Red Deer Polytechnic                        10
Southern Alberta Institute of Technology    10
St. Mary's University                       10
The King's University                       10
University of Alberta                       10
University of Calgary                       10
University of Lethbridge                    10
Name: Academic_Year, dtype: int64

In [68]:
print("FINAL DATA QUALITY CHECK")
print("-" * 40)

print(f"Rows: {len(df_long)}")
print(f"Columns: {len(df_long.columns)}")

print(
    "Standardized institutions:",
    df_long.loc[
        df_long["Record_Type"] == "Institution",
        "Institution_Standardized"
    ].nunique()
)

print(
    "Academic years:",
    df_long["Academic_Year"].nunique()
)

print(
    "Missing enrolment values:",
    df_long["Enrolment"].isna().sum()
)

print(
    "Duplicate institution-year records:",
    df_long.duplicated(
        subset=["Institution_Standardized", "Academic_Year"]
    ).sum()
)

print(
    "Negative enrolment values:",
    (df_long["Enrolment"] < 0).sum()
)

FINAL DATA QUALITY CHECK
----------------------------------------
Rows: 260
Columns: 9
Standardized institutions: 25
Academic years: 10
Missing enrolment values: 0
Duplicate institution-year records: 0
Negative enrolment values: 0

In [69]:
alberta_total = (
    df_long[
        df_long["Record_Type"] == "Province Total"
    ][
        ["Academic_Year", "Academic_Year_Start", "Enrolment"]
    ]
    .rename(columns={"Enrolment": "Reported_Alberta_Total"})
    .sort_values("Academic_Year_Start")
)

alberta_total

  Academic_Year  Academic_Year_Start  Reported_Alberta_Total
0     2014/2015                 2014                184026.0
1     2015/2016                 2015                185679.0
2     2016/2017                 2016                190947.0
3     2017/2018                 2017                194010.0
4     2018/2019                 2018                200391.0
5     2019/2020                 2019                203823.0
6     2020/2021                 2020                203523.0
7     2021/2022                 2021                203580.0
8     2022/2023                 2022                205734.0
9     2023/2024                 2023                216957.0

In [70]:
institution_sum = (
    df_long[
        df_long["Record_Type"] == "Institution"
    ]
    .groupby(
        ["Academic_Year", "Academic_Year_Start"],
        as_index=False
    )["Enrolment"]
    .sum()
    .rename(columns={"Enrolment": "Institution_Sum"})
    .sort_values("Academic_Year_Start")
)

institution_sum

  Academic_Year  Academic_Year_Start  Institution_Sum
0     2014/2015                 2014         184032.0
1     2015/2016                 2015         185691.0
2     2016/2017                 2016         190950.0
3     2017/2018                 2017         194013.0
4     2018/2019                 2018         200400.0
5     2019/2020                 2019         203817.0
6     2020/2021                 2020         203523.0
7     2021/2022                 2021         203589.0
8     2022/2023                 2022         205737.0
9     2023/2024                 2023         216963.0

In [71]:
reconciliation = alberta_total.merge(
    institution_sum,
    on=["Academic_Year", "Academic_Year_Start"],
    how="left"
)

In [72]:
reconciliation["Difference"] = (
    reconciliation["Reported_Alberta_Total"]
    - reconciliation["Institution_Sum"]
)

In [73]:
reconciliation["Difference_Pct"] = (
    reconciliation["Difference"]
    / reconciliation["Reported_Alberta_Total"]
    * 100
)

In [74]:
reconciliation

,Academic_Year,Academic_Year_Start,Reported_Alberta_Total,Institution_Sum,Difference,Difference_Pct
0,2014/2015,2014,184026.0,184032.0,-6.0,-0.003260
1,2015/2016,2015,185679.0,185691.0,-12.0,-0.006463
2,2016/2017,2016,190947.0,190950.0,-3.0,-0.001571
3,2017/2018,2017,194010.0,194013.0,-3.0,-0.001546
4,2018/2019,2018,200391.0,200400.0,-9.0,-0.004491
5,2019/2020,2019,203823.0,203817.0,6.0,0.002944
6,2020/2021,2020,203523.0,203523.0,0.0,0.000000
7,2021/2022,2021,203580.0,203589.0,-9.0,-0.004421
8,2022/2023,2022,205734.0,205737.0,-3.0,-0.001458
9,2023/2024,2023,216957.0,216963.0,-6.0,-0.002766

## Provincial Total Reconciliation

As a final validation step(above), the sum of institution-level enrolment
records was compared with Statistics Canada's reported Alberta
provincial total for each academic year.

This test is intended to identify potential differences in coverage,
classification, aggregation, or reporting before the dataset is used
for analytical modelling.

### Reconciliation Result

Institution-level enrolment totals were compared with the published
Alberta provincial totals for all 10 academic years.

Differences ranged from 0 to 12 students annually, representing less
than 0.01% of reported provincial enrolment in every year.

These minor discrepancies are consistent with Statistics Canada's
random-rounding methodology. Published values were therefore retained
without adjustment.

The reconciliation provides additional confidence that the cleaned
dataset accurately preserves the source data and that no material
records were lost during transformation.

In [76]:
df_final = df_long[
    [
        "Province",
        "Institution_Standardized",
        "Record_Type",
        "Academic_Year",
        "Academic_Year_Start",
        "Academic_Year_End",
        "Enrolment"
    ]
].copy()

In [77]:
df_final = df_final.rename(
    columns={
        "Institution_Standardized": "Institution"
    }
)

In [78]:
df_final = df_final.sort_values(
    by=["Institution", "Academic_Year_Start"]
).reset_index(drop=True)

In [79]:
df_final.head(15)

,Province,Institution,Record_Type,Academic_Year,Academic_Year_Start,Academic_Year_End,Enrolment
0,Alberta,Alberta,Province Total,2014/2015,2014,2015,184026.0
1,Alberta,Alberta,Province Total,2015/2016,2015,2016,185679.0
2,Alberta,Alberta,Province Total,2016/2017,2016,2017,190947.0
3,Alberta,Alberta,Province Total,2017/2018,2017,2018,194010.0
4,Alberta,Alberta,Province Total,2018/2019,2018,2019,200391.0
5,Alberta,Alberta,Province Total,2019/2020,2019,2020,203823.0
6,Alberta,Alberta,Province Total,2020/2021,2020,2021,203523.0
7,Alberta,Alberta,Province Total,2021/2022,2021,2022,203580.0
8,Alberta,Alberta,Province Total,2022/2023,2022,2023,205734.0
9,Alberta,Alberta,Province Total,2023/2024,2023,2024,216957.0
10,Alberta,Alberta University of the Arts,Institution,2014/2015,2014,2015,1116.0
11,Alberta,Alberta University of the Arts,Institution,2015/2016,2015,2016,1158.0
12,Alberta,Alberta University of the Arts,Institution,2016/2017,2016,2017,1140.0
13,Alberta,Alberta University of the Arts,Institution,2017/2018,2017,2018,1107.0
14,Alberta,Alberta University of the Arts,Institution,2018/2019,2018,2019,1077.0

In [80]:
df_final["Enrolment"] = df_final["Enrolment"].astype(int)

In [81]:
df_final.dtypes

Province                 str
Institution              str
Record_Type              str
Academic_Year            str
Academic_Year_Start    int64
Academic_Year_End      int64
Enrolment              int64
dtype: object

In [82]:
print("FINAL ANALYTICAL DATASET")
print("-" * 40)

print("Shape:", df_final.shape)
print("Missing values:", df_final.isna().sum().sum())

print(
    "Duplicate institution-year records:",
    df_final.duplicated(
        subset=["Institution", "Academic_Year"]
    ).sum()
)

print(
    "Academic years:",
    df_final["Academic_Year"].nunique()
)

print(
    "Institutions:",
    df_final.loc[
        df_final["Record_Type"] == "Institution",
        "Institution"
    ].nunique()
)

print(
    "Provincial aggregate records:",
    (df_final["Record_Type"] == "Province Total").sum()
)

FINAL ANALYTICAL DATASET
----------------------------------------
Shape: (260, 7)
Missing values: 0
Duplicate institution-year records: 0
Academic years: 10
Institutions: 25
Provincial aggregate records: 10

In [83]:
institution_list = (
    df_final.loc[
        df_final["Record_Type"] == "Institution",
        "Institution"
    ]
    .drop_duplicates()
    .sort_values()
    .tolist()
)

print("Number of institutions:", len(institution_list))

for i, institution in enumerate(institution_list, start=1):
    print(i, institution)

Number of institutions: 25
1 Alberta University of the Arts
2 Ambrose University
3 Athabasca University
4 Bow Valley College
5 Burman University
6 Concordia University of Edmonton
7 Grant MacEwan University
8 Keyano College
9 Lakeland College
10 Lethbridge College
11 Medicine Hat College
12 Mount Royal University
13 NorQuest College
14 Northern Alberta Institute of Technology
15 Northern Lakes College
16 Northwestern Polytechnic
17 Olds College
18 Portage College
19 Red Deer Polytechnic
20 Southern Alberta Institute of Technology
21 St. Mary's University
22 The King's University
23 University of Alberta
24 University of Calgary
25 University of Lethbridge

In [84]:
output_path = "../data/processed/alberta_enrolment_2014_2024_clean.csv"

df_final.to_csv(
    output_path,
    index=False
)

print(f"Clean dataset exported to: {output_path}")

Clean dataset exported to: ../data/processed/alberta_enrolment_2014_2024_clean.csv