# Alberta Post-Secondary Enrolment Analytics

## 03 — Student Status Data Cleaning

### Objective

Prepare Statistics Canada enrolment data for analysis of Canadian and
international student enrolment across Alberta postsecondary institutions
from 2014/15 through 2023/24.

### Student Status Categories

- Canadian students
- International students

### Cleaning Goals

- Preserve the original Statistics Canada extract
- Inspect the dataset structure before transformation
- Remove source metadata and non-data rows
- Standardize institution names where required
- Convert enrolment values to numeric format
- Reshape the dataset into analysis-ready long format
- Validate missing values and duplicate records
- Reconcile Canadian and international enrolment against the overall
  enrolment dataset where appropriate

In [1]:
import pandas as pd

In [2]:
file_path = "../data/raw/statcan_alberta_enrolment_student_status_2014_2024_raw.csv"

In [3]:
with open(file_path, "r", encoding="utf-8-sig") as file:
    for i in range(25):
        line = file.readline()
        print(i, repr(line))

0 '"Postsecondary enrolments, by detailed field of study, institution, and program and student characteristics 1 2 3 4 5"\n'
1 '"Frequency:\xa0Annual"\n'
2 '"Table: 37-10-0277-01"\n'
3 '"Release date: 2025-11-20"\n'
4 '"Geography: Canada, Geographical region of Canada, Province or territory"\n'
5 '""\n'
6 '""\n'
7 '\n'
8 '"Field of study 6 7 8","Total, field of study",,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n'
9 '"Program type","Total, program type",,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n'
10 '"Credential type","Total, credential type",,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n'
11 '"Institution type","Total, institution type",,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n'
12 '"Registration status","Total, registration status",,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n'
13 '"Status of student in Canada 9","Total, status of student in Canada",,,,,,,,,,"Canadian students",,,,,,,,,,"International students",,,,,,,,,\n'
14 '"Gender 10","Total, gender",,,,,,,,,,"Total, gender",,,,,,,,,,"Total, gender",,,,,,,,,\n'
15 '"Geography and institutions","2014 / 2015","2015 / 2016","2016 / 2017","2017 / 2018","2018 / 2019","2019 / 2020","2020 / 2021","2021 / 2022","2022 / 2023","2023 / 2024","2014 / 2015","2015 / 2016","2016 / 2017","2017 / 2018","2018 / 2019","2019 / 2020","2020 / 2021","2021 / 2022","2022 / 2023","2023 / 2024","2014 / 2015","2015 / 2016","2016 / 2017","2017 / 2018","2018 / 2019","2019 / 2020","2020 / 2021","2021 / 2022","2022 / 2023","2023 / 2024"\n'
16 ',"Number",,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n'
17 '"Alberta 11","184,026","185,679","190,947","194,010","200,391","203,823","203,523","203,580","205,734","216,957","167,463","167,946","172,506","175,065","178,617","179,178","179,850","178,239","175,698","179,535","16,458","17,478","18,303","18,798","21,663","24,636","23,667","25,311","30,018","37,416"\n'
18 '"University of Alberta, Alberta","38,520","37,716","38,244","39,363","40,017","40,590","42,270","43,905","44,535","45,306","31,689","31,041","31,467","32,043","32,292","32,382","34,329","35,688","36,063","36,972","6,831","6,672","6,777","7,305","7,716","8,205","7,938","8,214","8,466","8,331"\n'
19 '"Athabasca University, Alberta","17,577","17,331","17,346","16,941","18,561","18,930","20,535","17,127","16,458","16,005","17,211","16,860","16,836","16,371","17,979","18,279","19,908","16,668","16,008","15,486","354","429","468","531","537","651","630","456","450","516"\n'
20 '"University of Calgary, Alberta","31,308","31,749","33,189","33,903","34,785","35,556","36,543","37,200","37,680","38,715","28,200","28,398","29,697","30,195","30,582","30,693","31,512","31,029","30,765","31,602","3,111","3,351","3,492","3,708","4,203","4,860","5,031","6,168","6,915","7,113"\n'
21 '"Burman University, Alberta","474","471","456","435","435","459","390","339","348","333","423","414","390","375","351","366","300","273","288","261","51","57","63","63","84","93","90","69","60","72"\n'
22 '"Concordia University of Edmonton, Alberta","1,506","1,686","1,878","2,001","2,235","2,679","2,997","2,817","2,628","2,568","1,368","1,539","1,707","1,848","1,980","2,226","2,454","2,376","2,178","2,076","138","147","168","156","255","453","546","444","453","495"\n'
23 '"University of Lethbridge, Alberta","8,157","8,406","8,568","8,670","8,709","8,949","8,829","9,117","8,553","8,682","7,614","7,869","8,022","8,169","8,229","8,391","8,319","8,499","7,722","7,350","543","537","546","501","480","561","510","618","831","1,332"\n'
24 '"The King\'s University, Alberta","702","765","780","810","825","834","849","879","810","804","660","711","723","747","765","747","768","804","726","711","39","51","57","63","63","87","84","78","84","96"\n'

In [4]:
df_raw = pd.read_csv(
    file_path,
    skiprows=15
)

df_raw.shape

(44, 31)

In [5]:
df_raw.columns.tolist()

['Geography and institutions',
 '2014 / 2015',
 '2015 / 2016',
 '2016 / 2017',
 '2017 / 2018',
 '2018 / 2019',
 '2019 / 2020',
 '2020 / 2021',
 '2021 / 2022',
 '2022 / 2023',
 '2023 / 2024',
 '2014 / 2015.1',
 '2015 / 2016.1',
 '2016 / 2017.1',
 '2017 / 2018.1',
 '2018 / 2019.1',
 '2019 / 2020.1',
 '2020 / 2021.1',
 '2021 / 2022.1',
 '2022 / 2023.1',
 '2023 / 2024.1',
 '2014 / 2015.2',
 '2015 / 2016.2',
 '2016 / 2017.2',
 '2017 / 2018.2',
 '2018 / 2019.2',
 '2019 / 2020.2',
 '2020 / 2021.2',
 '2021 / 2022.2',
 '2022 / 2023.2',
 '2023 / 2024.2']

In [6]:
df_raw.head(10)

,Geography and institutions,2014 / 2015,2015 / 2016,2016 / 2017,2017 / 2018,2018 / 2019,2019 / 2020,2020 / 2021,2021 / 2022,2022 / 2023,...,2014 / 2015.2,2015 / 2016.2,2016 / 2017.2,2017 / 2018.2,2018 / 2019.2,2019 / 2020.2,2020 / 2021.2,2021 / 2022.2,2022 / 2023.2,2023 / 2024.2
0,NaN,Number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alberta 11,"184,026","185,679","190,947","194,010","200,391","203,823","203,523","203,580","205,734",...,"16,458","17,478","18,303","18,798","21,663","24,636","23,667","25,311","30,018","37,416"
2,"University of Alberta, Alberta","38,520","37,716","38,244","39,363","40,017","40,590","42,270","43,905","44,535",...,"6,831","6,672","6,777","7,305","7,716","8,205","7,938","8,214","8,466","8,331"
3,"Athabasca University, Alberta","17,577","17,331","17,346","16,941","18,561","18,930","20,535","17,127","16,458",...,354,429,468,531,537,651,630,456,450,516
4,"University of Calgary, Alberta","31,308","31,749","33,189","33,903","34,785","35,556","36,543","37,200","37,680",...,"3,111","3,351","3,492","3,708","4,203","4,860","5,031","6,168","6,915","7,113"
5,"Burman University, Alberta",474,471,456,435,435,459,390,339,348,...,51,57,63,63,84,93,90,69,60,72
6,"Concordia University of Edmonton, Alberta","1,506","1,686","1,878","2,001","2,235","2,679","2,997","2,817","2,628",...,138,147,168,156,255,453,546,444,453,495
7,"University of Lethbridge, Alberta","8,157","8,406","8,568","8,670","8,709","8,949","8,829","9,117","8,553",...,543,537,546,501,480,561,510,618,831,"1,332"
8,"The King's University, Alberta",702,765,780,810,825,834,849,879,810,...,39,51,57,63,63,87,84,78,84,96
9,"St. Mary's University, Alberta",732,771,789,888,921,999,"1,020","1,032",942,...,9,6,6,18,12,15,12,15,12,6

In [7]:
df_raw = pd.read_csv(
    file_path,
    skiprows=15
)

df_raw.shape

(44, 31)

In [8]:
df_raw.columns.tolist()

['Geography and institutions',
 '2014 / 2015',
 '2015 / 2016',
 '2016 / 2017',
 '2017 / 2018',
 '2018 / 2019',
 '2019 / 2020',
 '2020 / 2021',
 '2021 / 2022',
 '2022 / 2023',
 '2023 / 2024',
 '2014 / 2015.1',
 '2015 / 2016.1',
 '2016 / 2017.1',
 '2017 / 2018.1',
 '2018 / 2019.1',
 '2019 / 2020.1',
 '2020 / 2021.1',
 '2021 / 2022.1',
 '2022 / 2023.1',
 '2023 / 2024.1',
 '2014 / 2015.2',
 '2015 / 2016.2',
 '2016 / 2017.2',
 '2017 / 2018.2',
 '2018 / 2019.2',
 '2019 / 2020.2',
 '2020 / 2021.2',
 '2021 / 2022.2',
 '2022 / 2023.2',
 '2023 / 2024.2']

In [9]:
df_raw.head(10)

,Geography and institutions,2014 / 2015,2015 / 2016,2016 / 2017,2017 / 2018,2018 / 2019,2019 / 2020,2020 / 2021,2021 / 2022,2022 / 2023,...,2014 / 2015.2,2015 / 2016.2,2016 / 2017.2,2017 / 2018.2,2018 / 2019.2,2019 / 2020.2,2020 / 2021.2,2021 / 2022.2,2022 / 2023.2,2023 / 2024.2
0,NaN,Number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alberta 11,"184,026","185,679","190,947","194,010","200,391","203,823","203,523","203,580","205,734",...,"16,458","17,478","18,303","18,798","21,663","24,636","23,667","25,311","30,018","37,416"
2,"University of Alberta, Alberta","38,520","37,716","38,244","39,363","40,017","40,590","42,270","43,905","44,535",...,"6,831","6,672","6,777","7,305","7,716","8,205","7,938","8,214","8,466","8,331"
3,"Athabasca University, Alberta","17,577","17,331","17,346","16,941","18,561","18,930","20,535","17,127","16,458",...,354,429,468,531,537,651,630,456,450,516
4,"University of Calgary, Alberta","31,308","31,749","33,189","33,903","34,785","35,556","36,543","37,200","37,680",...,"3,111","3,351","3,492","3,708","4,203","4,860","5,031","6,168","6,915","7,113"
5,"Burman University, Alberta",474,471,456,435,435,459,390,339,348,...,51,57,63,63,84,93,90,69,60,72
6,"Concordia University of Edmonton, Alberta","1,506","1,686","1,878","2,001","2,235","2,679","2,997","2,817","2,628",...,138,147,168,156,255,453,546,444,453,495
7,"University of Lethbridge, Alberta","8,157","8,406","8,568","8,670","8,709","8,949","8,829","9,117","8,553",...,543,537,546,501,480,561,510,618,831,"1,332"
8,"The King's University, Alberta",702,765,780,810,825,834,849,879,810,...,39,51,57,63,63,87,84,78,84,96
9,"St. Mary's University, Alberta",732,771,789,888,921,999,"1,020","1,032",942,...,9,6,6,18,12,15,12,15,12,6

In [10]:
print("Dataset shape:", df_raw.shape)

print("\nColumns:")
for i, col in enumerate(df_raw.columns):
    print(i, col)

Dataset shape: (44, 31)

Columns:
0 Geography and institutions
1 2014 / 2015
2 2015 / 2016
3 2016 / 2017
4 2017 / 2018
5 2018 / 2019
6 2019 / 2020
7 2020 / 2021
8 2021 / 2022
9 2022 / 2023
10 2023 / 2024
11 2014 / 2015.1
12 2015 / 2016.1
13 2016 / 2017.1
14 2017 / 2018.1
15 2018 / 2019.1
16 2019 / 2020.1
17 2020 / 2021.1
18 2021 / 2022.1
19 2022 / 2023.1
20 2023 / 2024.1
21 2014 / 2015.2
22 2015 / 2016.2
23 2016 / 2017.2
24 2017 / 2018.2
25 2018 / 2019.2
26 2019 / 2020.2
27 2020 / 2021.2
28 2021 / 2022.2
29 2022 / 2023.2
30 2023 / 2024.2

In [11]:
df_raw = pd.read_csv(
    file_path,
    skiprows=15
)

df_raw.shape

(44, 31)

In [12]:
df_raw.head(10)

,Geography and institutions,2014 / 2015,2015 / 2016,2016 / 2017,2017 / 2018,2018 / 2019,2019 / 2020,2020 / 2021,2021 / 2022,2022 / 2023,...,2014 / 2015.2,2015 / 2016.2,2016 / 2017.2,2017 / 2018.2,2018 / 2019.2,2019 / 2020.2,2020 / 2021.2,2021 / 2022.2,2022 / 2023.2,2023 / 2024.2
0,NaN,Number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alberta 11,"184,026","185,679","190,947","194,010","200,391","203,823","203,523","203,580","205,734",...,"16,458","17,478","18,303","18,798","21,663","24,636","23,667","25,311","30,018","37,416"
2,"University of Alberta, Alberta","38,520","37,716","38,244","39,363","40,017","40,590","42,270","43,905","44,535",...,"6,831","6,672","6,777","7,305","7,716","8,205","7,938","8,214","8,466","8,331"
3,"Athabasca University, Alberta","17,577","17,331","17,346","16,941","18,561","18,930","20,535","17,127","16,458",...,354,429,468,531,537,651,630,456,450,516
4,"University of Calgary, Alberta","31,308","31,749","33,189","33,903","34,785","35,556","36,543","37,200","37,680",...,"3,111","3,351","3,492","3,708","4,203","4,860","5,031","6,168","6,915","7,113"
5,"Burman University, Alberta",474,471,456,435,435,459,390,339,348,...,51,57,63,63,84,93,90,69,60,72
6,"Concordia University of Edmonton, Alberta","1,506","1,686","1,878","2,001","2,235","2,679","2,997","2,817","2,628",...,138,147,168,156,255,453,546,444,453,495
7,"University of Lethbridge, Alberta","8,157","8,406","8,568","8,670","8,709","8,949","8,829","9,117","8,553",...,543,537,546,501,480,561,510,618,831,"1,332"
8,"The King's University, Alberta",702,765,780,810,825,834,849,879,810,...,39,51,57,63,63,87,84,78,84,96
9,"St. Mary's University, Alberta",732,771,789,888,921,999,"1,020","1,032",942,...,9,6,6,18,12,15,12,15,12,6

In [13]:
print("Dataset shape:", df_raw.shape)

print("\nColumns:")
for i, col in enumerate(df_raw.columns):
    print(i, col)

Dataset shape: (44, 31)

Columns:
0 Geography and institutions
1 2014 / 2015
2 2015 / 2016
3 2016 / 2017
4 2017 / 2018
5 2018 / 2019
6 2019 / 2020
7 2020 / 2021
8 2021 / 2022
9 2022 / 2023
10 2023 / 2024
11 2014 / 2015.1
12 2015 / 2016.1
13 2016 / 2017.1
14 2017 / 2018.1
15 2018 / 2019.1
16 2019 / 2020.1
17 2020 / 2021.1
18 2021 / 2022.1
19 2022 / 2023.1
20 2023 / 2024.1
21 2014 / 2015.2
22 2015 / 2016.2
23 2016 / 2017.2
24 2017 / 2018.2
25 2018 / 2019.2
26 2019 / 2020.2
27 2020 / 2021.2
28 2021 / 2022.2
29 2022 / 2023.2
30 2023 / 2024.2

In [14]:
df = df_raw.copy()

df = df[
    df["Geography and institutions"].notna()
].copy()

df = df[
    df["Geography and institutions"] != "Number"
].copy()

df.shape

(43, 31)

In [15]:
df["Geography and institutions"].tolist()

['Alberta 11',
 'University of Alberta, Alberta',
 'Athabasca University, Alberta',
 'University of Calgary, Alberta',
 'Burman University, Alberta',
 'Concordia University of Edmonton, Alberta',
 'University of Lethbridge, Alberta',
 "The King's University, Alberta",
 "St. Mary's University, Alberta",
 'Ambrose University, Alberta',
 'Grant MacEwan University, Alberta',
 'Mount Royal University, Alberta',
 'Alberta University of the Arts, Alberta 11',
 'Alberta College of Art and Design, Alberta 11',
 'Bow Valley College, Alberta',
 'Olds College, Alberta',
 'Lakeland College, Alberta',
 'Northwestern Polytechnic, Alberta',
 'Lethbridge College, Alberta',
 'Medicine Hat College, Alberta',
 'Keyano College, Alberta',
 'Red Deer Polytechnic, Alberta',
 'Northern Alberta Institute of Technology, Alberta',
 'Southern Alberta Institute of Technology, Alberta',
 'NorQuest College, Alberta',
 'Northern Lakes College, Alberta',
 'Portage College, Alberta',
 'Symbol legend:',
 '..',
 'Footnotes:',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 'How to cite: Statistics Canada. Table 37-10-0277-01\xa0 Postsecondary enrolments, by detailed field of study, institution, and program and student characteristics',
 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3710027701']

In [16]:
for i, value in enumerate(df["Geography and institutions"]):
    print(i, repr(value))

0 'Alberta 11'
1 'University of Alberta, Alberta'
2 'Athabasca University, Alberta'
3 'University of Calgary, Alberta'
4 'Burman University, Alberta'
5 'Concordia University of Edmonton, Alberta'
6 'University of Lethbridge, Alberta'
7 "The King's University, Alberta"
8 "St. Mary's University, Alberta"
9 'Ambrose University, Alberta'
10 'Grant MacEwan University, Alberta'
11 'Mount Royal University, Alberta'
12 'Alberta University of the Arts, Alberta 11'
13 'Alberta College of Art and Design, Alberta 11'
14 'Bow Valley College, Alberta'
15 'Olds College, Alberta'
16 'Lakeland College, Alberta'
17 'Northwestern Polytechnic, Alberta'
18 'Lethbridge College, Alberta'
19 'Medicine Hat College, Alberta'
20 'Keyano College, Alberta'
21 'Red Deer Polytechnic, Alberta'
22 'Northern Alberta Institute of Technology, Alberta'
23 'Southern Alberta Institute of Technology, Alberta'
24 'NorQuest College, Alberta'
25 'Northern Lakes College, Alberta'
26 'Portage College, Alberta'
27 'Symbol legend:'
28 '..'
29 'Footnotes:'
30 '1'
31 '2'
32 '3'
33 '4'
34 '5'
35 '6'
36 '7'
37 '8'
38 '9'
39 '10'
40 '11'
41 'How to cite: Statistics Canada. Table 37-10-0277-01\xa0 Postsecondary enrolments, by detailed field of study, institution, and program and student characteristics'
42 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3710027701'

In [17]:
df.shape

(43, 31)

In [18]:
df["Geography and institutions"].tolist()

['Alberta 11',
 'University of Alberta, Alberta',
 'Athabasca University, Alberta',
 'University of Calgary, Alberta',
 'Burman University, Alberta',
 'Concordia University of Edmonton, Alberta',
 'University of Lethbridge, Alberta',
 "The King's University, Alberta",
 "St. Mary's University, Alberta",
 'Ambrose University, Alberta',
 'Grant MacEwan University, Alberta',
 'Mount Royal University, Alberta',
 'Alberta University of the Arts, Alberta 11',
 'Alberta College of Art and Design, Alberta 11',
 'Bow Valley College, Alberta',
 'Olds College, Alberta',
 'Lakeland College, Alberta',
 'Northwestern Polytechnic, Alberta',
 'Lethbridge College, Alberta',
 'Medicine Hat College, Alberta',
 'Keyano College, Alberta',
 'Red Deer Polytechnic, Alberta',
 'Northern Alberta Institute of Technology, Alberta',
 'Southern Alberta Institute of Technology, Alberta',
 'NorQuest College, Alberta',
 'Northern Lakes College, Alberta',
 'Portage College, Alberta',
 'Symbol legend:',
 '..',
 'Footnotes:',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 'How to cite: Statistics Canada. Table 37-10-0277-01\xa0 Postsecondary enrolments, by detailed field of study, institution, and program and student characteristics',
 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3710027701']

In [19]:
symbol_index = df[
    df["Geography and institutions"] == "Symbol legend:"
].index[0]

df = df.loc[df.index < symbol_index].copy()

df.shape

(27, 31)

In [20]:
df["Geography and institutions"].tolist()

['Alberta 11',
 'University of Alberta, Alberta',
 'Athabasca University, Alberta',
 'University of Calgary, Alberta',
 'Burman University, Alberta',
 'Concordia University of Edmonton, Alberta',
 'University of Lethbridge, Alberta',
 "The King's University, Alberta",
 "St. Mary's University, Alberta",
 'Ambrose University, Alberta',
 'Grant MacEwan University, Alberta',
 'Mount Royal University, Alberta',
 'Alberta University of the Arts, Alberta 11',
 'Alberta College of Art and Design, Alberta 11',
 'Bow Valley College, Alberta',
 'Olds College, Alberta',
 'Lakeland College, Alberta',
 'Northwestern Polytechnic, Alberta',
 'Lethbridge College, Alberta',
 'Medicine Hat College, Alberta',
 'Keyano College, Alberta',
 'Red Deer Polytechnic, Alberta',
 'Northern Alberta Institute of Technology, Alberta',
 'Southern Alberta Institute of Technology, Alberta',
 'NorQuest College, Alberta',
 'Northern Lakes College, Alberta',
 'Portage College, Alberta']

In [21]:
df = df.rename(
    columns={"Geography and institutions": "Institution_Raw"}
)

df["Institution"] = (
    df["Institution_Raw"]
    .str.replace(r", Alberta 11$", "", regex=True)
    .str.replace(r", Alberta$", "", regex=True)
    .str.replace(r" 11$", "", regex=True)
    .str.strip()
)

df[["Institution_Raw", "Institution"]].head(15)

,Institution_Raw,Institution
1,Alberta 11,Alberta
2,"University of Alberta, Alberta",University of Alberta
3,"Athabasca University, Alberta",Athabasca University
4,"University of Calgary, Alberta",University of Calgary
5,"Burman University, Alberta",Burman University
6,"Concordia University of Edmonton, Alberta",Concordia University of Edmonton
7,"University of Lethbridge, Alberta",University of Lethbridge
8,"The King's University, Alberta",The King's University
9,"St. Mary's University, Alberta",St. Mary's University
10,"Ambrose University, Alberta",Ambrose University
11,"Grant MacEwan University, Alberta",Grant MacEwan University
12,"Mount Royal University, Alberta",Mount Royal University
13,"Alberta University of the Arts, Alberta 11",Alberta University of the Arts
14,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design
15,"Bow Valley College, Alberta",Bow Valley College

In [22]:
df["Institution_Standardized"] = df["Institution"].replace({
    "Alberta College of Art and Design": "Alberta University of the Arts"
})

In [23]:
df[
    df["Institution"].str.contains(
        "Alberta University|Alberta College",
        case=False,
        na=False
    )
][["Institution_Raw", "Institution", "Institution_Standardized"]]

,Institution_Raw,Institution,Institution_Standardized
13,"Alberta University of the Arts, Alberta 11",Alberta University of the Arts,Alberta University of the Arts
14,"Alberta College of Art and Design, Alberta 11",Alberta College of Art and Design,Alberta University of the Arts

In [24]:
total_cols = df.columns[1:11].tolist()
canadian_cols = df.columns[11:21].tolist()
international_cols = df.columns[21:31].tolist()

print("TOTAL:")
print(total_cols)

print("\nCANADIAN:")
print(canadian_cols)

print("\nINTERNATIONAL:")
print(international_cols)

TOTAL:
['2014 / 2015', '2015 / 2016', '2016 / 2017', '2017 / 2018', '2018 / 2019', '2019 / 2020', '2020 / 2021', '2021 / 2022', '2022 / 2023', '2023 / 2024']

CANADIAN:
['2014 / 2015.1', '2015 / 2016.1', '2016 / 2017.1', '2017 / 2018.1', '2018 / 2019.1', '2019 / 2020.1', '2020 / 2021.1', '2021 / 2022.1', '2022 / 2023.1', '2023 / 2024.1']

INTERNATIONAL:
['2014 / 2015.2', '2015 / 2016.2', '2016 / 2017.2', '2017 / 2018.2', '2018 / 2019.2', '2019 / 2020.2', '2020 / 2021.2', '2021 / 2022.2', '2022 / 2023.2', '2023 / 2024.2']

In [25]:
total_cols = [
    "2014 / 2015",
    "2015 / 2016",
    "2016 / 2017",
    "2017 / 2018",
    "2018 / 2019",
    "2019 / 2020",
    "2020 / 2021",
    "2021 / 2022",
    "2022 / 2023",
    "2023 / 2024"
]

canadian_cols = [col + ".1" for col in total_cols]
international_cols = [col + ".2" for col in total_cols]

print("Total:", total_cols)
print("\nCanadian:", canadian_cols)
print("\nInternational:", international_cols)

Total: ['2014 / 2015', '2015 / 2016', '2016 / 2017', '2017 / 2018', '2018 / 2019', '2019 / 2020', '2020 / 2021', '2021 / 2022', '2022 / 2023', '2023 / 2024']

Canadian: ['2014 / 2015.1', '2015 / 2016.1', '2016 / 2017.1', '2017 / 2018.1', '2018 / 2019.1', '2019 / 2020.1', '2020 / 2021.1', '2021 / 2022.1', '2022 / 2023.1', '2023 / 2024.1']

International: ['2014 / 2015.2', '2015 / 2016.2', '2016 / 2017.2', '2017 / 2018.2', '2018 / 2019.2', '2019 / 2020.2', '2020 / 2021.2', '2021 / 2022.2', '2022 / 2023.2', '2023 / 2024.2']

## Reshape Student Status Data

The Statistics Canada extract stores total, Canadian, and international
enrolment in three separate 10-year column blocks.

Each block is reshaped into long format and assigned a student-status
category so that each record represents one institution, one academic
year, and one student-status group.

In [26]:
def reshape_status_block(data, columns, status_name):
    
    block = data[
        ["Institution_Raw", "Institution", "Institution_Standardized"] + columns
    ].copy()

    block = block.melt(
        id_vars=[
            "Institution_Raw",
            "Institution",
            "Institution_Standardized"
        ],
        value_vars=columns,
        var_name="Academic_Year",
        value_name="Enrolment"
    )

    block["Student_Status"] = status_name

    return block

In [27]:
df_total = reshape_status_block(
    df,
    total_cols,
    "Total"
)

df_canadian = reshape_status_block(
    df,
    canadian_cols,
    "Canadian"
)

df_international = reshape_status_block(
    df,
    international_cols,
    "International"
)

In [28]:
print("Total:", df_total.shape)
print("Canadian:", df_canadian.shape)
print("International:", df_international.shape)

Total: (270, 6)
Canadian: (270, 6)
International: (270, 6)

In [29]:
for block in [df_total, df_canadian, df_international]:
    block["Academic_Year"] = (
        block["Academic_Year"]
        .str.replace(r"\.\d+$", "", regex=True)
        .str.replace(" ", "", regex=False)
    )

In [30]:
print(df_total["Academic_Year"].unique())
print(df_canadian["Academic_Year"].unique())
print(df_international["Academic_Year"].unique())

<ArrowStringArray>
['2014/2015', '2015/2016', '2016/2017', '2017/2018', '2018/2019', '2019/2020',
 '2020/2021', '2021/2022', '2022/2023', '2023/2024']
Length: 10, dtype: str
<ArrowStringArray>
['2014/2015', '2015/2016', '2016/2017', '2017/2018', '2018/2019', '2019/2020',
 '2020/2021', '2021/2022', '2022/2023', '2023/2024']
Length: 10, dtype: str
<ArrowStringArray>
['2014/2015', '2015/2016', '2016/2017', '2017/2018', '2018/2019', '2019/2020',
 '2020/2021', '2021/2022', '2022/2023', '2023/2024']
Length: 10, dtype: str

In [31]:
df_long = pd.concat(
    [
        df_total,
        df_canadian,
        df_international
    ],
    ignore_index=True
)

df_long.shape

(810, 6)

In [32]:
df_long["Student_Status"].value_counts()

Student_Status
Total            270
Canadian         270
International    270
Name: count, dtype: int64

In [33]:
df_long["Enrolment"] = (
    df_long["Enrolment"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

df_long["Enrolment"] = pd.to_numeric(
    df_long["Enrolment"],
    errors="coerce"
)

In [34]:
df_long.dtypes

Institution_Raw                 str
Institution                     str
Institution_Standardized        str
Academic_Year                   str
Enrolment                   float64
Student_Status                  str
dtype: object

In [35]:
df_long["Enrolment"].isna().sum()

np.int64(30)

In [36]:
df_long[
    df_long["Enrolment"].isna()
][
    [
        "Institution",
        "Institution_Standardized",
        "Academic_Year",
        "Student_Status",
        "Enrolment"
    ]
]

,Institution,Institution_Standardized,Academic_Year,Student_Status,Enrolment
12,Alberta University of the Arts,Alberta University of the Arts,2014/2015,Total,NaN
39,Alberta University of the Arts,Alberta University of the Arts,2015/2016,Total,NaN
66,Alberta University of the Arts,Alberta University of the Arts,2016/2017,Total,NaN
93,Alberta University of the Arts,Alberta University of the Arts,2017/2018,Total,NaN
121,Alberta College of Art and Design,Alberta University of the Arts,2018/2019,Total,NaN
148,Alberta College of Art and Design,Alberta University of the Arts,2019/2020,Total,NaN
175,Alberta College of Art and Design,Alberta University of the Arts,2020/2021,Total,NaN
202,Alberta College of Art and Design,Alberta University of the Arts,2021/2022,Total,NaN
229,Alberta College of Art and Design,Alberta University of the Arts,2022/2023,Total,NaN
256,Alberta College of Art and Design,Alberta University of the Arts,2023/2024,Total,NaN
282,Alberta University of the Arts,Alberta University of the Arts,2014/2015,Canadian,NaN
309,Alberta University of the Arts,Alberta University of the Arts,2015/2016,Canadian,NaN
336,Alberta University of the Arts,Alberta University of the Arts,2016/2017,Canadian,NaN
363,Alberta University of the Arts,Alberta University of the Arts,2017/2018,Canadian,NaN
391,Alberta College of Art and Design,Alberta University of the Arts,2018/2019,Canadian,NaN
418,Alberta College of Art and Design,Alberta University of the Arts,2019/2020,Canadian,NaN
445,Alberta College of Art and Design,Alberta University of the Arts,2020/2021,Canadian,NaN
472,Alberta College of Art and Design,Alberta University of the Arts,2021/2022,Canadian,NaN
499,Alberta College of Art and Design,Alberta University of the Arts,2022/2023,Canadian,NaN
526,Alberta College of Art and Design,Alberta University of the Arts,2023/2024,Canadian,NaN
552,Alberta University of the Arts,Alberta University of the Arts,2014/2015,International,NaN
579,Alberta University of the Arts,Alberta University of the Arts,2015/2016,International,NaN
606,Alberta University of the Arts,Alberta University of the Arts,2016/2017,International,NaN
633,Alberta University of the Arts,Alberta University of the Arts,2017/2018,International,NaN
661,Alberta College of Art and Design,Alberta University of the Arts,2018/2019,International,NaN
688,Alberta College of Art and Design,Alberta University of the Arts,2019/2020,International,NaN
715,Alberta College of Art and Design,Alberta University of the Arts,2020/2021,International,NaN
742,Alberta College of Art and Design,Alberta University of the Arts,2021/2022,International,NaN
769,Alberta College of Art and Design,Alberta University of the Arts,2022/2023,International,NaN
796,Alberta College of Art and Design,Alberta University of the Arts,2023/2024,International,NaN

In [37]:
df_long = df_long[
    ~(
        (
            df_long["Institution_Standardized"]
            == "Alberta University of the Arts"
        )
        &
        (
            df_long["Enrolment"].isna()
        )
    )
].copy()

df_long = df_long.reset_index(drop=True)

In [38]:
df_long.shape

(780, 6)

In [39]:
df_long["Province"] = "Alberta"

df_long["Record_Type"] = df_long[
    "Institution_Standardized"
].apply(
    lambda x: "Province Total"
    if x == "Alberta"
    else "Institution"
)

In [40]:
df_long["Academic_Year_Start"] = (
    df_long["Academic_Year"]
    .str[:4]
    .astype(int)
)

df_long["Academic_Year_End"] = (
    df_long["Academic_Year_Start"] + 1
)

In [41]:
df_long[
    [
        "Institution_Standardized",
        "Academic_Year",
        "Student_Status",
        "Enrolment"
    ]
].head(20)

            Institution_Standardized Academic_Year Student_Status  Enrolment
0                            Alberta     2014/2015          Total   184026.0
1              University of Alberta     2014/2015          Total    38520.0
2               Athabasca University     2014/2015          Total    17577.0
3              University of Calgary     2014/2015          Total    31308.0
4                  Burman University     2014/2015          Total      474.0
5   Concordia University of Edmonton     2014/2015          Total     1506.0
6           University of Lethbridge     2014/2015          Total     8157.0
7              The King's University     2014/2015          Total      702.0
8              St. Mary's University     2014/2015          Total      732.0
9                 Ambrose University     2014/2015          Total      519.0
10          Grant MacEwan University     2014/2015          Total    15870.0
11            Mount Royal University     2014/2015          Total    12372.0
12    Alberta University of the Arts     2014/2015          Total     1116.0
13                Bow Valley College     2014/2015          Total     6891.0
14                      Olds College     2014/2015          Total     1371.0
15                  Lakeland College     2014/2015          Total     1959.0
16          Northwestern Polytechnic     2014/2015          Total     1995.0
17                Lethbridge College     2014/2015          Total     4413.0
18              Medicine Hat College     2014/2015          Total     2271.0
19                    Keyano College     2014/2015          Total     1434.0

In [42]:
validation = df_long.pivot_table(
    index=[
        "Institution_Standardized",
        "Academic_Year"
    ],
    columns="Student_Status",
    values="Enrolment",
    aggfunc="sum"
).reset_index()

In [43]:
validation.head()

Student_Status,Institution_Standardized,Academic_Year,Canadian,International,Total
0,Alberta,2014/2015,167463.0,16458.0,184026.0
1,Alberta,2015/2016,167946.0,17478.0,185679.0
2,Alberta,2016/2017,172506.0,18303.0,190947.0
3,Alberta,2017/2018,175065.0,18798.0,194010.0
4,Alberta,2018/2019,178617.0,21663.0,200391.0

In [44]:
validation["Calculated_Total"] = (
    validation["Canadian"]
    + validation["International"]
)

In [45]:
validation["Difference"] = (
    validation["Total"]
    - validation["Calculated_Total"]
)

In [46]:
validation[
    [
        "Institution_Standardized",
        "Academic_Year",
        "Canadian",
        "International",
        "Total",
        "Calculated_Total",
        "Difference"
    ]
].head(20)

Student_Status,Institution_Standardized,Academic_Year,Canadian,International,Total,Calculated_Total,Difference
0,Alberta,2014/2015,167463.0,16458.0,184026.0,183921.0,105.0
1,Alberta,2015/2016,167946.0,17478.0,185679.0,185424.0,255.0
2,Alberta,2016/2017,172506.0,18303.0,190947.0,190809.0,138.0
3,Alberta,2017/2018,175065.0,18798.0,194010.0,193863.0,147.0
4,Alberta,2018/2019,178617.0,21663.0,200391.0,200280.0,111.0
5,Alberta,2019/2020,179178.0,24636.0,203823.0,203814.0,9.0
6,Alberta,2020/2021,179850.0,23667.0,203523.0,203517.0,6.0
7,Alberta,2021/2022,178239.0,25311.0,203580.0,203550.0,30.0
8,Alberta,2022/2023,175698.0,30018.0,205734.0,205716.0,18.0
9,Alberta,2023/2024,179535.0,37416.0,216957.0,216951.0,6.0
10,Alberta University of the Arts,2014/2015,1047.0,63.0,1116.0,1110.0,6.0
11,Alberta University of the Arts,2015/2016,1083.0,69.0,1158.0,1152.0,6.0
12,Alberta University of the Arts,2016/2017,1068.0,66.0,1140.0,1134.0,6.0
13,Alberta University of the Arts,2017/2018,1026.0,81.0,1107.0,1107.0,0.0
14,Alberta University of the Arts,2018/2019,993.0,87.0,1077.0,1080.0,-3.0
15,Alberta University of the Arts,2019/2020,1056.0,90.0,1143.0,1146.0,-3.0
16,Alberta University of the Arts,2020/2021,1017.0,87.0,1110.0,1104.0,6.0
17,Alberta University of the Arts,2021/2022,1011.0,78.0,1089.0,1089.0,0.0
18,Alberta University of the Arts,2022/2023,1026.0,102.0,1131.0,1128.0,3.0
19,Alberta University of the Arts,2023/2024,1101.0,99.0,1200.0,1200.0,0.0

In [47]:
df_long.shape

(780, 10)

In [48]:
df_long["Enrolment"].isna().sum()

np.int64(0)

In [49]:
df_long["Student_Status"].value_counts()

Student_Status
Total            260
Canadian         260
International    260
Name: count, dtype: int64

In [50]:
validation["Difference"].value_counts().sort_index()

Difference
-3.0       43
 0.0      125
 3.0       54
 6.0        9
 9.0        3
 12.0       3
 15.0       3
 18.0       1
 21.0       1
 30.0       1
 39.0       2
 42.0       3
 45.0       1
 48.0       1
 57.0       1
 63.0       2
 66.0       1
 99.0       1
 105.0      1
 111.0      1
 138.0      1
 147.0      1
 255.0      1
Name: count, dtype: int64

In [51]:
validation["Difference"].value_counts().sort_index()

Difference
-3.0       43
 0.0      125
 3.0       54
 6.0        9
 9.0        3
 12.0       3
 15.0       3
 18.0       1
 21.0       1
 30.0       1
 39.0       2
 42.0       3
 45.0       1
 48.0       1
 57.0       1
 63.0       2
 66.0       1
 99.0       1
 105.0      1
 111.0      1
 138.0      1
 147.0      1
 255.0      1
Name: count, dtype: int64

In [52]:
print("Number of validation records:", len(validation))

print(
    "Exact matches:",
    (validation["Difference"] == 0).sum()
)

print(
    "Within ±3:",
    (validation["Difference"].abs() <= 3).sum()
)

print(
    "Within ±10:",
    (validation["Difference"].abs() <= 10).sum()
)

print(
    "Largest absolute difference:",
    validation["Difference"].abs().max()
)

print(
    "Mean absolute difference:",
    validation["Difference"].abs().mean()
)

Number of validation records: 260
Exact matches: 125
Within ±3: 222
Within ±10: 234
Largest absolute difference: 255.0
Mean absolute difference: 7.3961538461538465

In [53]:
validation[
    [
        "Institution_Standardized",
        "Academic_Year",
        "Total",
        "Canadian",
        "International",
        "Difference"
    ]
].assign(
    Abs_Difference=lambda x: x["Difference"].abs()
).sort_values(
    "Abs_Difference",
    ascending=False
).head(15)

Student_Status,Institution_Standardized,Academic_Year,Total,Canadian,International,Difference,Abs_Difference
1,Alberta,2015/2016,185679.0,167946.0,17478.0,255.0,255.0
3,Alberta,2017/2018,194010.0,175065.0,18798.0,147.0,147.0
2,Alberta,2016/2017,190947.0,172506.0,18303.0,138.0,138.0
4,Alberta,2018/2019,200391.0,178617.0,21663.0,111.0,111.0
0,Alberta,2014/2015,184026.0,167463.0,16458.0,105.0,105.0
121,Mount Royal University,2015/2016,12216.0,11712.0,405.0,99.0,99.0
131,NorQuest College,2015/2016,5097.0,4827.0,204.0,66.0,66.0
44,Bow Valley College,2018/2019,8451.0,6813.0,1575.0,63.0,63.0
43,Bow Valley College,2017/2018,7506.0,6420.0,1023.0,63.0,63.0
120,Mount Royal University,2014/2015,12372.0,11895.0,420.0,57.0,57.0
142,Northern Alberta Institute of Technology,2016/2017,12687.0,11217.0,1422.0,48.0,48.0
34,Athabasca University,2018/2019,18561.0,17979.0,537.0,45.0,45.0
31,Athabasca University,2015/2016,17331.0,16860.0,429.0,42.0,42.0
141,Northern Alberta Institute of Technology,2015/2016,11784.0,10416.0,1326.0,42.0,42.0
32,Athabasca University,2016/2017,17346.0,16836.0,468.0,42.0,42.0

In [54]:
validation["Difference_Pct"] = (
    validation["Difference"].abs()
    / validation["Total"]
    * 100
)

validation[
    [
        "Institution_Standardized",
        "Academic_Year",
        "Total",
        "Canadian",
        "International",
        "Difference",
        "Difference_Pct"
    ]
].sort_values(
    "Difference_Pct",
    ascending=False
).head(15)

Student_Status,Institution_Standardized,Academic_Year,Total,Canadian,International,Difference,Difference_Pct
131,NorQuest College,2015/2016,5097.0,4827.0,204.0,66.0,1.294879
21,Ambrose University,2015/2016,576.0,555.0,15.0,6.0,1.041667
57,Burman University,2021/2022,339.0,273.0,69.0,-3.0,0.884956
43,Bow Valley College,2017/2018,7506.0,6420.0,1023.0,63.0,0.839329
121,Mount Royal University,2015/2016,12216.0,11712.0,405.0,99.0,0.810413
44,Bow Valley College,2018/2019,8451.0,6813.0,1575.0,63.0,0.745474
53,Burman University,2017/2018,435.0,375.0,63.0,-3.0,0.689655
52,Burman University,2016/2017,456.0,390.0,63.0,3.0,0.657895
188,Portage College,2022/2023,1398.0,1200.0,189.0,9.0,0.643777
29,Ambrose University,2023/2024,552.0,510.0,39.0,3.0,0.543478
16,Alberta University of the Arts,2020/2021,1110.0,1017.0,87.0,6.0,0.540541
10,Alberta University of the Arts,2014/2015,1116.0,1047.0,63.0,6.0,0.537634
12,Alberta University of the Arts,2016/2017,1140.0,1068.0,66.0,6.0,0.526316
11,Alberta University of the Arts,2015/2016,1158.0,1083.0,69.0,6.0,0.518135
24,Ambrose University,2018/2019,594.0,567.0,30.0,-3.0,0.505051

In [55]:
print(
    "Maximum percentage discrepancy:",
    round(validation["Difference_Pct"].max(), 3),
    "%"
)

print(
    "Mean percentage discrepancy:",
    round(validation["Difference_Pct"].mean(), 3),
    "%"
)

print(
    "Records within 0.5%:",
    (validation["Difference_Pct"] <= 0.5).sum(),
    "of",
    len(validation)
)

print(
    "Records within 1%:",
    (validation["Difference_Pct"] <= 1).sum(),
    "of",
    len(validation)
)

Maximum percentage discrepancy: 1.295 %
Mean percentage discrepancy: 0.11 %
Records within 0.5%: 245 of 260
Records within 1%: 258 of 260

## Final Data Quality Check

Before saving the cleaned student-status dataset, perform final checks for:

- Missing enrolment values
- Duplicate institution-year-status records
- Negative enrolment values
- Number of institutions
- Number of academic years
- Number of records by student status

In [56]:
print("FINAL DATA QUALITY CHECK — DATASET 2")
print("-" * 45)

print("Rows:", len(df_long))
print("Columns:", df_long.shape[1])

print(
    "Institutions:",
    df_long["Institution_Standardized"].nunique()
)

print(
    "Academic years:",
    df_long["Academic_Year"].nunique()
)

print(
    "Missing enrolment values:",
    df_long["Enrolment"].isna().sum()
)

print(
    "Negative enrolment values:",
    (df_long["Enrolment"] < 0).sum()
)

print(
    "Duplicate institution-year-status records:",
    df_long.duplicated(
        subset=[
            "Institution_Standardized",
            "Academic_Year",
            "Student_Status"
        ]
    ).sum()
)

print("\nRecords by student status:")
print(df_long["Student_Status"].value_counts())

FINAL DATA QUALITY CHECK — DATASET 2
---------------------------------------------
Rows: 780
Columns: 10
Institutions: 26
Academic years: 10
Missing enrolment values: 0
Negative enrolment values: 0
Duplicate institution-year-status records: 0

Records by student status:
Student_Status
Total            260
Canadian         260
International    260
Name: count, dtype: int64

## Save Cleaned Dataset

Export the validated long-format student-status dataset for use in the exploratory analysis.

In [57]:
output_path = "../data/processed/alberta_student_status_clean.csv"

df_long.to_csv(
    output_path,
    index=False
)

print("Saved cleaned Dataset 2 to:")
print(output_path)

print("\nSaved shape:", df_long.shape)

Saved cleaned Dataset 2 to:
../data/processed/alberta_student_status_clean.csv

Saved shape: (780, 10)